services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-northwind
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=London4567!
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
      - ./scripts:/scripts
    command: /bin/bash -c "(/opt/mssql/bin/sqlservr &) && sleep 20 && /scripts/init-db.sh"

volumes:
  sql_data: