services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./site-content:/usr/share/nginx/html:ro
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
